import PropTypes from 'prop-types';

export const propTypes = {
  id: PropTypes.string.isRequired,
  children: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
  selector: PropTypes.string,
  position: PropTypes.string,
  wrapper: PropTypes.string,
  filter: PropTypes.string,
  gap: PropTypes.number,
  boundedGap: PropTypes.number,
  topGap: PropTypes.number,
  rightGap: PropTypes.number,
  leftGap: PropTypes.number,
  downGap: PropTypes.number,
  strategy: PropTypes.string,
  refreshStrategy: PropTypes.string,
  memory: PropTypes.bool,
  active: PropTypes.bool,
  onRight: PropTypes.func,
  onLeft: PropTypes.func,
  onUp: PropTypes.func,
  onDown: PropTypes.func,
  onEnter: PropTypes.func,
  debounce: PropTypes.number,
  triggerClick: PropTypes.bool,
  longPress: PropTypes.bool,
  onLeftExit: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  onRightExit: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  onUpExit: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  onDownExit: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  priority: PropTypes.number,
  direction: PropTypes.string,
};

export const defaultProps = {
  selector: 'li',
  active: true,
  strategy: 'none',
  refreshStrategy: 'first',
  memory: false,
  filter: null,
  gap: 20,
  boundedGap: 0,
  topGap: 0,
  rightGap: 0,
  leftGap: 0,
  downGap: 0,
  longPress: true,
  triggerClick: true,
  priority: 0,
};
